export const userData = [
    {
      name: 'Jan',
     "Active User": 4000,
    },
    {
        name: 'Feb',
       "Active User": 5000,
      },
      {
        name: 'Mar',
       "Active User": 3000,
      },
      {
        name: 'Apr',
       "Active User": 7000,
      },
      {
        name: 'May',
       "Active User": 2000,
      },
      {
        name: 'Jun',
       "Active User": 1000,
      },
      {
        name: 'Jul',
       "Active User": 6000,
      },
      {
        name: 'Agu',
       "Active User": 8000,
      },
      {
        name: 'Sep',
       "Active User": 9000,
      },
      {
        name: 'Oct',
       "Active User": 1000,
      },
      {
        name: 'Nov',
       "Active User": 8000,
      },
      {
        name: 'Dec',
       "Active User": 12000,
      },

  ];

  export const userRows = [
    { id: 1,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$160.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 2,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$140.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 3,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$20.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 4,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$10.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 5,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$500.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 6,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "550.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 7,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$60.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4"
     },
     { id: 8,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$180.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 9,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$220.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
     { id: 10,
        username: "Jon Snow",
        email: "thiagoliveira01@globomail.com",
        status: 'active',
        transaction: "$120.00",
        avatar: "https://avatars.githubusercontent.com/u/77520434?v=4",
     },
  
  ];

  export const productsRows = [
   { id: 1,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$160.00",
       img: '/apple.jpg',
    },
    { id: 2,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$140.00",
       img: '/apple.jpg',
    },
    { id: 3,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$20.00",
       img: '/apple.jpg',
    },
    { id: 4,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$10.00",
       img: '/apple.jpg',
    },
    { id: 5,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$500.00",
       img: '/apple.jpg',
    },
    { id: 6,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "550.00",
       img: '/apple.jpg',
    },
    { id: 7,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$60.00",
       img: '/apple.jpg'
    },
    { id: 8,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$180.00",
       img: '/apple.jpg',
    },
    { id: 9,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$220.00",
       img: '/apple.jpg',
    },
    { id: 10,
       name: "Apple Airpods",
       stock: 123,
       status: 'active',
       price: "$120.00",
       img: '/apple.jpg',
    },
 
 ];